services:
  - type: web
    name: expenseflow-api
    env: python
    plan: free
    buildCommand: bash ./build.sh
    startCommand: cd backend && gunicorn expense_tracker.wsgi:application --bind 0.0.0.0:$PORT
    healthCheckPath: /
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: expense_tracker.settings
      - key: DJANGO_DEBUG
        value: false
      - key: DJANGO_ALLOWED_HOSTS
        value: ""
      - key: PYTHON_VERSION
        value: 3.12.8
    envVarGroups:
      - id: render
        vars:
          - key: DATABASE_URL
            fromDatabase:
              name: expenseflow-db
              property: connectionString
          - key: DJANGO_SECRET_KEY
            sync: false

  - type: pserv
    name: expenseflow-db
    dbName: expenseflow
    ipAllowList: []
    plan: free
